# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

import os
import sys
import re
from docutils import nodes
from docutils.parsers.rst import roles
from docutils.parsers.rst import Directive, directives

sys.path.insert(0, os.path.abspath("../.."))

from MHCXGraph import __version__

project = 'MHCXGraph'
copyright = '2026, CNPEM'
author = 'CNPEM'
version = ".".join(__version__.split('.')[0:2])
release = __version__

# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.napoleon",
    "sphinx.ext.doctest",
    "sphinx.ext.intersphinx",
    "sphinx.ext.todo",
    "sphinx.ext.coverage",
    "sphinx.ext.mathjax",
    "sphinx.ext.ifconfig",
    "sphinx.ext.viewcode",
    "sphinx.ext.githubpages",
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

autosummary_generate = True
# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = ".rst"

# The master toctree document.
master_doc = "index"

autodoc_mock_imports = [
    "freesasa",
    "pandas",
    "pydssp",
    "scipy",
    "bottleneck",
    "Bio",
    "seaborn",
    "statsmodels"
]
# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "furo"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]
html_css_files = ['custom.css']

# HTML favicon
html_favicon = "_static/icon.ico"

# HTML logo
html_logo = "_static/logo.png"


# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = "MHCXGraphdoc"


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',
    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, "MHCXGraph.tex", "MHCXGraph Documentation", "CNPEM", "manual"),
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [(master_doc, "MHCXGraph", "MHCXGraph Documentation", [author], 1)]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc,
        "MHCXGraph",
        "MHCXGraphg Documentation",
        author,
        "MHCXGraph",
        "A python package for graph-based detection of structurally similar surface regions in protein complexes, with a focus on peptide–MHC (pMHC) systems involved in T cell receptor (TCR) recognition.",
        "Miscellaneous",
    ),
]


# -- Options for Epub output -------------------------------------------------

# Bibliographic Dublin Core info.
epub_title = project

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#
# epub_identifier = ''

# A unique identification for the text.
#
# epub_uid = ''

# A list of files that should not be packed into the epub file.
epub_exclude_files = ["search.html"]

# -- Extension configuration -------------------------------------------------

# -- Options for intersphinx extension ---------------------------------------

# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {'python': ('https://docs.python.org/3', None)}

# -- Options for todo extension ----------------------------------------------

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True

def is_float_regex(value):
    return bool(re.match(r'^[-+]?[0-9]*\.?[0-9]+$', value))

class MHCXParamDirective(Directive):
    required_arguments = 1
    has_content = True

    option_spec = {
        "type": directives.unchanged,
        "default": directives.unchanged,
    }

    def run(self):
        env = self.state.document.settings.env
        name = self.arguments[0].strip()

        target_id = f"mhcx-param-{name}"
        target_node = nodes.target('', '', ids=[target_id])

        # HEADER (subsection-like)
        header = nodes.container(classes=["mhcx-param"])

        title = nodes.paragraph(classes=["mhcx-param-title"])

        title += nodes.inline(text=name + ":", classes=["mhcx-param-name"])

        # META
        meta_parts = []
        if "type" in self.options:
            meta_parts.append(f"type: {self.options['type']}")
        if "default" in self.options:
            if self.options["type"] == "string":
                meta_parts.append(f'default: "{self.options["default"]}"')
            else:
                meta_parts.append(f'default: {self.options["default"]}')

        if meta_parts:
            meta_text = " (" + ", ".join(meta_parts) + ")"
            title += nodes.inline(text=meta_text, classes=["mhcx-param-meta"])

        header += title

        # CONTENT (normal flow)
        content_nodes = []
        if self.content:
            content = nodes.paragraph()
            self.state.nested_parse(self.content, self.content_offset, content)
            content_nodes.append(content)

        # register for references
        if not hasattr(env, "mhcx_params"):
            env.mhcx_params = {}
        env.mhcx_params[name] = (env.docname, target_id)

        return [target_node, header] + content_nodes

def mhcx_param_role(name, rawtext, text, lineno, inliner, options={}, content=[]):
    env = inliner.document.settings.env
    param_name = text.strip()
    
    if not hasattr(env, "mhcx_params") or param_name not in env.mhcx_params:
        return [nodes.literal(text=param_name)], []

    docname, target_id = env.mhcx_params[param_name]

    builder = env.app.builder
    fromdoc = env.docname
    refuri = builder.get_relative_uri(fromdoc, docname) + "#" + target_id

    literal = nodes.literal(param_name, param_name)
    refnode = nodes.reference("", "", literal, refuri=refuri)

    return [refnode], []

def setup(app):
    app.add_directive("mhcx-param", MHCXParamDirective)
    roles.register_local_role("mhcx-param", mhcx_param_role)
